### ISSUE TITLE
groups 'kdc' and 'ldap' are used interchangeably

### ISSUE THREAD

**Issue by jusstol** [TOSIT-IO/tdp-collection-extras#31]
Hi everyone 👋  and thank you for your amazing work.

In _deploy-ldap-kerberos.yml_ from tdp-getting-started, OpenLDAP and Kerberos servers are both installed on the `kdc` group :

```yaml
# tdp-getting-started : deploy-ldap-kerberos.yml
- hosts: kdc
  tasks:
    - import_role:
        name: ansible_roles/collections/ansible_collections/tosit/tdp_extra/roles/ansible-ldap-kerberos
```

but you'll find direct reference to the first item of the `ldap` group or `kdc` group in certain situations like this one :

```yaml
# tdp-collection-extras : roles/ansible-ldap-kerberos/defaults/main.yml
ldap_server: "{{ groups['ldap'][0] }}.{{ domain }}"
...
kerberos_server: "{{ groups['ldap'][0] }}.{{ domain }}"  # <-- kerberos_server from ldap group
```

In other words, nothing is installed using the ldap group, but this group is referenced afterwards.

Everything works fine since by default the host in the `ldap` group is the same as the one in the `kdc` group, but I feel like these groups aren't really useful as long as we can't separate openldap from kdc server.

What are your thoughts on this ? I might submit a PR to better separate ldap from kdc if you think it's worth it.
