### ISSUE TITLE
some roles can't be imported with their FQCN (dash forbidden)

### ISSUE THREAD

**Issue by jusstol** [TOSIT-IO/tdp-collection-extras#75]
## the situation
I chose to install all tdp collections with ansible-galaxy (I'm using Ansible 2.11.11), as dependencies, which works fine.

In most cases I can import playbook from a collection with its FQCN name like this :
````yaml
- import_playbook: tosit.tdp.meta.hdfs
# instead of : ansible_roles/collections/ansible_collections/tosit/tdp/playbooks/meta/hdfs.yml
````
And a role like this :
````yaml
- hosts: all
  roles:
    - tosit.tdp.utils.user
# instead of ansible_roles/collections/ansible_collections/tosit/tdp/roles/utils/user
````
Or a specific task like this :
````yaml
- hosts: all
  - tasks:
    - import_role: tosit.tdp.hdfs.client
      tasks_from: install

# instead of
# - hosts: all
#   - tasks:
#     - import_role: livraison/installation/ansible_roles/collections/ansible_collections/tosit/tdp/roles/hdfs/client
#       tasks_from: install
````
## the problem
There are some roles defined in tdp-collection-extras that I cannot import because they all have the same error :
```yaml
- hosts: all
  become: yes
  tasks:
    - name: Common setup and configuration accross all ansible hosts
      import_role:
        name: tosit.tdp_extra.ansible-tdp-common-actions

# leads to :
ERROR! the role 'ansible_roles/collections/ansible_collections/tosit/tdp_extra/roles/ansible-tdp-common-actions' was not found in [list of my ansible paths]
```
## the cause
Roles names in collections **must not** contain dashes (`-`).

Here are some references from the latest Ansible documentation.

- https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html#roles-directory
> Role names are now limited to contain only lowercase alphanumeric characters, plus _ and start with an alpha character.

> The directory name of the role is used as the role name. Therefore, the directory name must comply with the above role name rules. The collection import into Galaxy will fail if a role name does not comply with these rules.
- https://docs.ansible.com/ansible/latest/dev_guide/migrating_roles.html#example-migrating-a-standalone-role-with-plugins-to-a-collection
> In this example we have a standalone role called my-standalone-role.webapp to emulate a standalone role that contains dashes in the name **(which is not valid in collections)**
- https://docs.ansible.com/ansible/latest/user_guide/collections_using.html :
> The dash - character is not valid for playbook names in collections.

## the solution
Replace all dashes (`-`) with underscores (`_`) in roles names.  
For example the folder _./roles/ansible-tdp-common-actions_ would be renamed _./roles/ansible_tdp_common_actions_.

I tried this already and it works. With that minor needed update, tdp-collection-extras could be used as a functionning collection installed via ansible-galaxy.
