### ISSUE TITLE
Ansible-ssh-deployment - Why group value is set to user ?

### ISSUE THREAD

**Issue by ChristopheLRTE** [TOSIT-IO/tdp-collection-extras#78]
Hello,

Is there any reason why the task `Ensure ssh dir exists` [here](https://github.com/TOSIT-IO/tdp-collection-extras/blob/master/roles/ansible-ssh-deployment/tasks/generate-user-ssh-keys.yml) checks that group value is equal to user (_i.e. owner_) value and not the group we want to set by ourselves ? As a reminder, the involved ansible code :
```
- block:
  - name: Ensure ssh dir exists
    file:
      path: "{{ remote_ssh_dir }}"
      state: directory
      owner: "{{ owner }}"
      group: "{{ owner }}"
      mode: 0660
```
Thank you very much for your help,
C.L.
